### ISSUE TITLE
Support Metadata Message

### ISSUE THREAD

**Issue by DamienDeepgram** [deepgram/deepgram-rust-sdk#97]
Confirm if the Metadata Message is getting propagated when the stream is closed

- Without Callback
- With Callback

**Comment by bd-g** [comment]
Metadata is returned in two places:

- Attached to each `TranscriptResponse` is [metadata](https://github.com/deepgram/deepgram-rust-sdk/blob/b2455057617337cccad72af9cecf75a06cdb101b/src/common/stream_response.rs#L80) including the model info and request ID 
- At the end of the stream, the [`TerminalResponse`](https://github.com/deepgram/deepgram-rust-sdk/blob/b2455057617337cccad72af9cecf75a06cdb101b/src/common/stream_response.rs#L127) gives metadata like stream creation, request ID, and duration.
